### ISSUE TITLE
Botocore 1.13.38 unsupported version of python-dateutil 2.8.0+

### ISSUE THREAD

**Issue by ldoming** [artsy/jenkins-backup-s3#17]
I encountered this error when I use jenkins in docker with tag 2.197 >

```shell
jenkins@0bf6fe53e749:/$ backup-jenkins --bucket-region=us-west-XX \
>                --bucket=XXXXXXXXXXXX \
>                --bucket-prefix=jenkins-backups/$JENKINS_SERVER \
>                create \
>                --jenkins-home=$JENKINS_HOME \
>                --include-builds
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 854, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (python-dateutil 2.8.1 (/usr/local/lib/python3.5/dist-packages), Requirement.parse('python-dateutil<2.8.1,>=2.1; python_version >= "2.7"'), {'botocore'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/backup-jenkins", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 657, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 670, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 854, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (python-dateutil 2.8.1 (/usr/local/lib/python3.5/dist-packages), Requirement.parse('python-dateutil<2.8.1,>=2.1; python_version >= "2.7"'), {'botocore'})
```

I managed to fix this 
https://github.com/ldoming/jenkins-backup-s3/commit/6c40b2e35d2f2f4131b3d18ebcf5b48986320a26

**Comment by mikejw** [comment]
I'm getting this too.

**Comment by izakp** [comment]
We can loosen dependencies - why did you not open a PR?
