### ISSUE TITLE
pruning object does not work. 

### ISSUE THREAD

**Issue by mchodson** [artsy/jenkins-backup-s3#7]
if i use this script to make a backup i cannot delete with the script using the prune action. i can delete the object manually/directly however. i suspect there is something about the IAM role requirements that is not listed, or some libs are outdated. 

ex command run that fails:
$ backup-jenkins --bucket <BUCKET_NAME> --bucket-region us-west-2 prune 1

here is error:
Traceback (most recent call last):
  File "/usr/local/bin/backup-jenkins", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/jenkins_backup_s3/backup.py", line 249, in main
    cli(obj={})
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jenkins_backup_s3/backup.py", line 209, in prune
    _delete_command(backup_id, ctx.obj['BUCKET'], ctx.obj['BUCKET_PREFIX'], ctx.obj['BUCKET_REGION'], dry_run)
  File "/usr/local/lib/python2.7/dist-packages/jenkins_backup_s3/backup.py", line 186, in _delete_command
    s3.delete(backup_id)
  File "/usr/local/lib/python2.7/dist-packages/jenkins_backup_s3/backup.py", line 62, in delete
    s3_object = self.s3.Object(self.__bucket, key).delete()
  File "/usr/local/lib/python2.7/dist-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the DeleteObject operation: Access Denied

**Comment by izakp** [comment]
Check your Boto credentials https://boto3.readthedocs.io/en/latest/guide/configuration.html

**Comment by mchodson** [comment]
that was not the issue. the issue is with oudated libs. I modified the versions you freeze at to be more in line with current AWS cli install. That fixed it.
